// Code generated by Kitex v0.16.1. DO NOT EDIT.

package driverservice

import (
	"context"
	driver0 "driver/taketaxi/common/kitexGen/driver"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Create(ctx context.Context, req *driver0.CreateDriverReq, callOptions ...callopt.Option) (r *driver0.CreateDriverResp, err error)
	Get(ctx context.Context, req *driver0.GetDriverReq, callOptions ...callopt.Option) (r *driver0.GetDriverResp, err error)
	List(ctx context.Context, req *driver0.ListDriverReq, callOptions ...callopt.Option) (r *driver0.ListDriverResp, err error)
	Update(ctx context.Context, req *driver0.UpdateDriverReq, callOptions ...callopt.Option) (r *driver0.UpdateDriverResp, err error)
	Delete(ctx context.Context, req *driver0.DeleteDriverReq, callOptions ...callopt.Option) (r *driver0.DeleteDriverResp, err error)
	GoOnline(ctx context.Context, req *driver0.GoOnlineReq, callOptions ...callopt.Option) (r *driver0.GoOnlineResp, err error)
	SetIdle(ctx context.Context, req *driver0.SetIdleReq, callOptions ...callopt.Option) (r *driver0.SetIdleResp, err error)
	StartListening(ctx context.Context, req *driver0.StartListeningReq, callOptions ...callopt.Option) (r *driver0.StartListeningResp, err error)
	GoOffline(ctx context.Context, req *driver0.GoOfflineReq, callOptions ...callopt.Option) (r *driver0.GoOfflineResp, err error)
	ReportLocation(ctx context.Context, req *driver0.ReportLocationReq, callOptions ...callopt.Option) (r *driver0.ReportLocationResp, err error)
	DispatchOrder(ctx context.Context, req *driver0.DispatchOrderReq, callOptions ...callopt.Option) (r *driver0.DispatchOrderResp, err error)
	AcceptOrder(ctx context.Context, req *driver0.AcceptOrderReq, callOptions ...callopt.Option) (r *driver0.AcceptOrderResp, err error)
	RejectOrder(ctx context.Context, req *driver0.RejectOrderReq, callOptions ...callopt.Option) (r *driver0.RejectOrderResp, err error)
	CancelOrder(ctx context.Context, req *driver0.CancelOrderReq, callOptions ...callopt.Option) (r *driver0.CancelOrderResp, err error)
	DriverArrive(ctx context.Context, req *driver0.DriverArriveReq, callOptions ...callopt.Option) (r *driver0.DriverArriveResp, err error)
	StartTrip(ctx context.Context, req *driver0.StartTripReq, callOptions ...callopt.Option) (r *driver0.StartTripResp, err error)
	EndTrip(ctx context.Context, req *driver0.EndTripReq, callOptions ...callopt.Option) (r *driver0.EndTripResp, err error)
	VerifyPassengerPhone(ctx context.Context, req *driver0.VerifyPassengerPhoneReq, callOptions ...callopt.Option) (r *driver0.VerifyPassengerPhoneResp, err error)
	ListPoolOrders(ctx context.Context, req *driver0.ListPoolOrdersReq, callOptions ...callopt.Option) (r *driver0.ListPoolOrdersResp, err error)
	GrabOrder(ctx context.Context, req *driver0.GrabOrderReq, callOptions ...callopt.Option) (r *driver0.GrabOrderResp, err error)
	ListOrders(ctx context.Context, req *driver0.ListOrdersReq, callOptions ...callopt.Option) (r *driver0.ListOrdersResp, err error)
	GetOrder(ctx context.Context, req *driver0.GetOrderReq, callOptions ...callopt.Option) (r *driver0.GetOrderResp, err error)
	GetTodayStats(ctx context.Context, req *driver0.GetTodayStatsReq, callOptions ...callopt.Option) (r *driver0.TodayStatsResp, err error)
	GetCurrentOrder(ctx context.Context, req *driver0.GetCurrentOrderReq, callOptions ...callopt.Option) (r *driver0.CurrentOrderResp, err error)
	GetWallet(ctx context.Context, req *driver0.GetWalletReq, callOptions ...callopt.Option) (r *driver0.WalletResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDriverServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDriverServiceClient struct {
	*kClient
}

func (p *kDriverServiceClient) Create(ctx context.Context, req *driver0.CreateDriverReq, callOptions ...callopt.Option) (r *driver0.CreateDriverResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Create(ctx, req)
}

func (p *kDriverServiceClient) Get(ctx context.Context, req *driver0.GetDriverReq, callOptions ...callopt.Option) (r *driver0.GetDriverResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Get(ctx, req)
}

func (p *kDriverServiceClient) List(ctx context.Context, req *driver0.ListDriverReq, callOptions ...callopt.Option) (r *driver0.ListDriverResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.List(ctx, req)
}

func (p *kDriverServiceClient) Update(ctx context.Context, req *driver0.UpdateDriverReq, callOptions ...callopt.Option) (r *driver0.UpdateDriverResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Update(ctx, req)
}

func (p *kDriverServiceClient) Delete(ctx context.Context, req *driver0.DeleteDriverReq, callOptions ...callopt.Option) (r *driver0.DeleteDriverResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, req)
}

func (p *kDriverServiceClient) GoOnline(ctx context.Context, req *driver0.GoOnlineReq, callOptions ...callopt.Option) (r *driver0.GoOnlineResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GoOnline(ctx, req)
}

func (p *kDriverServiceClient) SetIdle(ctx context.Context, req *driver0.SetIdleReq, callOptions ...callopt.Option) (r *driver0.SetIdleResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetIdle(ctx, req)
}

func (p *kDriverServiceClient) StartListening(ctx context.Context, req *driver0.StartListeningReq, callOptions ...callopt.Option) (r *driver0.StartListeningResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartListening(ctx, req)
}

func (p *kDriverServiceClient) GoOffline(ctx context.Context, req *driver0.GoOfflineReq, callOptions ...callopt.Option) (r *driver0.GoOfflineResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GoOffline(ctx, req)
}

func (p *kDriverServiceClient) ReportLocation(ctx context.Context, req *driver0.ReportLocationReq, callOptions ...callopt.Option) (r *driver0.ReportLocationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReportLocation(ctx, req)
}

func (p *kDriverServiceClient) DispatchOrder(ctx context.Context, req *driver0.DispatchOrderReq, callOptions ...callopt.Option) (r *driver0.DispatchOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DispatchOrder(ctx, req)
}

func (p *kDriverServiceClient) AcceptOrder(ctx context.Context, req *driver0.AcceptOrderReq, callOptions ...callopt.Option) (r *driver0.AcceptOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AcceptOrder(ctx, req)
}

func (p *kDriverServiceClient) RejectOrder(ctx context.Context, req *driver0.RejectOrderReq, callOptions ...callopt.Option) (r *driver0.RejectOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RejectOrder(ctx, req)
}

func (p *kDriverServiceClient) CancelOrder(ctx context.Context, req *driver0.CancelOrderReq, callOptions ...callopt.Option) (r *driver0.CancelOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelOrder(ctx, req)
}

func (p *kDriverServiceClient) DriverArrive(ctx context.Context, req *driver0.DriverArriveReq, callOptions ...callopt.Option) (r *driver0.DriverArriveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DriverArrive(ctx, req)
}

func (p *kDriverServiceClient) StartTrip(ctx context.Context, req *driver0.StartTripReq, callOptions ...callopt.Option) (r *driver0.StartTripResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartTrip(ctx, req)
}

func (p *kDriverServiceClient) EndTrip(ctx context.Context, req *driver0.EndTripReq, callOptions ...callopt.Option) (r *driver0.EndTripResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EndTrip(ctx, req)
}

func (p *kDriverServiceClient) VerifyPassengerPhone(ctx context.Context, req *driver0.VerifyPassengerPhoneReq, callOptions ...callopt.Option) (r *driver0.VerifyPassengerPhoneResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyPassengerPhone(ctx, req)
}

func (p *kDriverServiceClient) ListPoolOrders(ctx context.Context, req *driver0.ListPoolOrdersReq, callOptions ...callopt.Option) (r *driver0.ListPoolOrdersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPoolOrders(ctx, req)
}

func (p *kDriverServiceClient) GrabOrder(ctx context.Context, req *driver0.GrabOrderReq, callOptions ...callopt.Option) (r *driver0.GrabOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GrabOrder(ctx, req)
}

func (p *kDriverServiceClient) ListOrders(ctx context.Context, req *driver0.ListOrdersReq, callOptions ...callopt.Option) (r *driver0.ListOrdersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOrders(ctx, req)
}

func (p *kDriverServiceClient) GetOrder(ctx context.Context, req *driver0.GetOrderReq, callOptions ...callopt.Option) (r *driver0.GetOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrder(ctx, req)
}

func (p *kDriverServiceClient) GetTodayStats(ctx context.Context, req *driver0.GetTodayStatsReq, callOptions ...callopt.Option) (r *driver0.TodayStatsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTodayStats(ctx, req)
}

func (p *kDriverServiceClient) GetCurrentOrder(ctx context.Context, req *driver0.GetCurrentOrderReq, callOptions ...callopt.Option) (r *driver0.CurrentOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCurrentOrder(ctx, req)
}

func (p *kDriverServiceClient) GetWallet(ctx context.Context, req *driver0.GetWalletReq, callOptions ...callopt.Option) (r *driver0.WalletResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetWallet(ctx, req)
}
