// Code generated by Kitex v0.16.1. DO NOT EDIT.

package driverservice

import (
	"context"
	driver "driver/taketaxi/common/kitexGen/driver"
	driver0 "driver/taketaxi/common/kitexGen/driver"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Create": kitex.NewMethodInfo(
		createHandler,
		newDriverServiceCreateArgs,
		newDriverServiceCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Get": kitex.NewMethodInfo(
		getHandler,
		newDriverServiceGetArgs,
		newDriverServiceGetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"List": kitex.NewMethodInfo(
		listHandler,
		newDriverServiceListArgs,
		newDriverServiceListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Update": kitex.NewMethodInfo(
		updateHandler,
		newDriverServiceUpdateArgs,
		newDriverServiceUpdateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Delete": kitex.NewMethodInfo(
		deleteHandler,
		newDriverServiceDeleteArgs,
		newDriverServiceDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GoOnline": kitex.NewMethodInfo(
		goOnlineHandler,
		newDriverServiceGoOnlineArgs,
		newDriverServiceGoOnlineResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetIdle": kitex.NewMethodInfo(
		setIdleHandler,
		newDriverServiceSetIdleArgs,
		newDriverServiceSetIdleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StartListening": kitex.NewMethodInfo(
		startListeningHandler,
		newDriverServiceStartListeningArgs,
		newDriverServiceStartListeningResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GoOffline": kitex.NewMethodInfo(
		goOfflineHandler,
		newDriverServiceGoOfflineArgs,
		newDriverServiceGoOfflineResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReportLocation": kitex.NewMethodInfo(
		reportLocationHandler,
		newDriverServiceReportLocationArgs,
		newDriverServiceReportLocationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DispatchOrder": kitex.NewMethodInfo(
		dispatchOrderHandler,
		newDriverServiceDispatchOrderArgs,
		newDriverServiceDispatchOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AcceptOrder": kitex.NewMethodInfo(
		acceptOrderHandler,
		newDriverServiceAcceptOrderArgs,
		newDriverServiceAcceptOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RejectOrder": kitex.NewMethodInfo(
		rejectOrderHandler,
		newDriverServiceRejectOrderArgs,
		newDriverServiceRejectOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelOrder": kitex.NewMethodInfo(
		cancelOrderHandler,
		newDriverServiceCancelOrderArgs,
		newDriverServiceCancelOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DriverArrive": kitex.NewMethodInfo(
		driverArriveHandler,
		newDriverServiceDriverArriveArgs,
		newDriverServiceDriverArriveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StartTrip": kitex.NewMethodInfo(
		startTripHandler,
		newDriverServiceStartTripArgs,
		newDriverServiceStartTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EndTrip": kitex.NewMethodInfo(
		endTripHandler,
		newDriverServiceEndTripArgs,
		newDriverServiceEndTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyPassengerPhone": kitex.NewMethodInfo(
		verifyPassengerPhoneHandler,
		newDriverServiceVerifyPassengerPhoneArgs,
		newDriverServiceVerifyPassengerPhoneResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListPoolOrders": kitex.NewMethodInfo(
		listPoolOrdersHandler,
		newDriverServiceListPoolOrdersArgs,
		newDriverServiceListPoolOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GrabOrder": kitex.NewMethodInfo(
		grabOrderHandler,
		newDriverServiceGrabOrderArgs,
		newDriverServiceGrabOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListOrders": kitex.NewMethodInfo(
		listOrdersHandler,
		newDriverServiceListOrdersArgs,
		newDriverServiceListOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrder": kitex.NewMethodInfo(
		getOrderHandler,
		newDriverServiceGetOrderArgs,
		newDriverServiceGetOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTodayStats": kitex.NewMethodInfo(
		getTodayStatsHandler,
		newDriverServiceGetTodayStatsArgs,
		newDriverServiceGetTodayStatsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCurrentOrder": kitex.NewMethodInfo(
		getCurrentOrderHandler,
		newDriverServiceGetCurrentOrderArgs,
		newDriverServiceGetCurrentOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetWallet": kitex.NewMethodInfo(
		getWalletHandler,
		newDriverServiceGetWalletArgs,
		newDriverServiceGetWalletResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	driverServiceServiceInfo                = NewServiceInfo()
	driverServiceServiceInfoForClient       = NewServiceInfoForClient()
	driverServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return driverServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return driverServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return driverServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DriverService"
	handlerType := (*driver.DriverService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "driver",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceCreateArgs)
	realResult := result.(*driver.DriverServiceCreateResult)
	success, err := handler.(driver.DriverService).Create(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceCreateArgs() interface{} {
	return driver.NewDriverServiceCreateArgs()
}

func newDriverServiceCreateResult() interface{} {
	return driver.NewDriverServiceCreateResult()
}

func getHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGetArgs)
	realResult := result.(*driver.DriverServiceGetResult)
	success, err := handler.(driver.DriverService).Get(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGetArgs() interface{} {
	return driver.NewDriverServiceGetArgs()
}

func newDriverServiceGetResult() interface{} {
	return driver.NewDriverServiceGetResult()
}

func listHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceListArgs)
	realResult := result.(*driver.DriverServiceListResult)
	success, err := handler.(driver.DriverService).List(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceListArgs() interface{} {
	return driver.NewDriverServiceListArgs()
}

func newDriverServiceListResult() interface{} {
	return driver.NewDriverServiceListResult()
}

func updateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceUpdateArgs)
	realResult := result.(*driver.DriverServiceUpdateResult)
	success, err := handler.(driver.DriverService).Update(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceUpdateArgs() interface{} {
	return driver.NewDriverServiceUpdateArgs()
}

func newDriverServiceUpdateResult() interface{} {
	return driver.NewDriverServiceUpdateResult()
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceDeleteArgs)
	realResult := result.(*driver.DriverServiceDeleteResult)
	success, err := handler.(driver.DriverService).Delete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceDeleteArgs() interface{} {
	return driver.NewDriverServiceDeleteArgs()
}

func newDriverServiceDeleteResult() interface{} {
	return driver.NewDriverServiceDeleteResult()
}

func goOnlineHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGoOnlineArgs)
	realResult := result.(*driver.DriverServiceGoOnlineResult)
	success, err := handler.(driver.DriverService).GoOnline(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGoOnlineArgs() interface{} {
	return driver.NewDriverServiceGoOnlineArgs()
}

func newDriverServiceGoOnlineResult() interface{} {
	return driver.NewDriverServiceGoOnlineResult()
}

func setIdleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceSetIdleArgs)
	realResult := result.(*driver.DriverServiceSetIdleResult)
	success, err := handler.(driver.DriverService).SetIdle(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceSetIdleArgs() interface{} {
	return driver.NewDriverServiceSetIdleArgs()
}

func newDriverServiceSetIdleResult() interface{} {
	return driver.NewDriverServiceSetIdleResult()
}

func startListeningHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceStartListeningArgs)
	realResult := result.(*driver.DriverServiceStartListeningResult)
	success, err := handler.(driver.DriverService).StartListening(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceStartListeningArgs() interface{} {
	return driver.NewDriverServiceStartListeningArgs()
}

func newDriverServiceStartListeningResult() interface{} {
	return driver.NewDriverServiceStartListeningResult()
}

func goOfflineHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGoOfflineArgs)
	realResult := result.(*driver.DriverServiceGoOfflineResult)
	success, err := handler.(driver.DriverService).GoOffline(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGoOfflineArgs() interface{} {
	return driver.NewDriverServiceGoOfflineArgs()
}

func newDriverServiceGoOfflineResult() interface{} {
	return driver.NewDriverServiceGoOfflineResult()
}

func reportLocationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceReportLocationArgs)
	realResult := result.(*driver.DriverServiceReportLocationResult)
	success, err := handler.(driver.DriverService).ReportLocation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceReportLocationArgs() interface{} {
	return driver.NewDriverServiceReportLocationArgs()
}

func newDriverServiceReportLocationResult() interface{} {
	return driver.NewDriverServiceReportLocationResult()
}

func dispatchOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceDispatchOrderArgs)
	realResult := result.(*driver.DriverServiceDispatchOrderResult)
	success, err := handler.(driver.DriverService).DispatchOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceDispatchOrderArgs() interface{} {
	return driver.NewDriverServiceDispatchOrderArgs()
}

func newDriverServiceDispatchOrderResult() interface{} {
	return driver.NewDriverServiceDispatchOrderResult()
}

func acceptOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceAcceptOrderArgs)
	realResult := result.(*driver.DriverServiceAcceptOrderResult)
	success, err := handler.(driver.DriverService).AcceptOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceAcceptOrderArgs() interface{} {
	return driver.NewDriverServiceAcceptOrderArgs()
}

func newDriverServiceAcceptOrderResult() interface{} {
	return driver.NewDriverServiceAcceptOrderResult()
}

func rejectOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceRejectOrderArgs)
	realResult := result.(*driver.DriverServiceRejectOrderResult)
	success, err := handler.(driver.DriverService).RejectOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceRejectOrderArgs() interface{} {
	return driver.NewDriverServiceRejectOrderArgs()
}

func newDriverServiceRejectOrderResult() interface{} {
	return driver.NewDriverServiceRejectOrderResult()
}

func cancelOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceCancelOrderArgs)
	realResult := result.(*driver.DriverServiceCancelOrderResult)
	success, err := handler.(driver.DriverService).CancelOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceCancelOrderArgs() interface{} {
	return driver.NewDriverServiceCancelOrderArgs()
}

func newDriverServiceCancelOrderResult() interface{} {
	return driver.NewDriverServiceCancelOrderResult()
}

func driverArriveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceDriverArriveArgs)
	realResult := result.(*driver.DriverServiceDriverArriveResult)
	success, err := handler.(driver.DriverService).DriverArrive(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceDriverArriveArgs() interface{} {
	return driver.NewDriverServiceDriverArriveArgs()
}

func newDriverServiceDriverArriveResult() interface{} {
	return driver.NewDriverServiceDriverArriveResult()
}

func startTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceStartTripArgs)
	realResult := result.(*driver.DriverServiceStartTripResult)
	success, err := handler.(driver.DriverService).StartTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceStartTripArgs() interface{} {
	return driver.NewDriverServiceStartTripArgs()
}

func newDriverServiceStartTripResult() interface{} {
	return driver.NewDriverServiceStartTripResult()
}

func endTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceEndTripArgs)
	realResult := result.(*driver.DriverServiceEndTripResult)
	success, err := handler.(driver.DriverService).EndTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceEndTripArgs() interface{} {
	return driver.NewDriverServiceEndTripArgs()
}

func newDriverServiceEndTripResult() interface{} {
	return driver.NewDriverServiceEndTripResult()
}

func verifyPassengerPhoneHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceVerifyPassengerPhoneArgs)
	realResult := result.(*driver.DriverServiceVerifyPassengerPhoneResult)
	success, err := handler.(driver.DriverService).VerifyPassengerPhone(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceVerifyPassengerPhoneArgs() interface{} {
	return driver.NewDriverServiceVerifyPassengerPhoneArgs()
}

func newDriverServiceVerifyPassengerPhoneResult() interface{} {
	return driver.NewDriverServiceVerifyPassengerPhoneResult()
}

func listPoolOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceListPoolOrdersArgs)
	realResult := result.(*driver.DriverServiceListPoolOrdersResult)
	success, err := handler.(driver.DriverService).ListPoolOrders(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceListPoolOrdersArgs() interface{} {
	return driver.NewDriverServiceListPoolOrdersArgs()
}

func newDriverServiceListPoolOrdersResult() interface{} {
	return driver.NewDriverServiceListPoolOrdersResult()
}

func grabOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGrabOrderArgs)
	realResult := result.(*driver.DriverServiceGrabOrderResult)
	success, err := handler.(driver.DriverService).GrabOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGrabOrderArgs() interface{} {
	return driver.NewDriverServiceGrabOrderArgs()
}

func newDriverServiceGrabOrderResult() interface{} {
	return driver.NewDriverServiceGrabOrderResult()
}

func listOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceListOrdersArgs)
	realResult := result.(*driver.DriverServiceListOrdersResult)
	success, err := handler.(driver.DriverService).ListOrders(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceListOrdersArgs() interface{} {
	return driver.NewDriverServiceListOrdersArgs()
}

func newDriverServiceListOrdersResult() interface{} {
	return driver.NewDriverServiceListOrdersResult()
}

func getOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGetOrderArgs)
	realResult := result.(*driver.DriverServiceGetOrderResult)
	success, err := handler.(driver.DriverService).GetOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGetOrderArgs() interface{} {
	return driver.NewDriverServiceGetOrderArgs()
}

func newDriverServiceGetOrderResult() interface{} {
	return driver.NewDriverServiceGetOrderResult()
}

func getTodayStatsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGetTodayStatsArgs)
	realResult := result.(*driver.DriverServiceGetTodayStatsResult)
	success, err := handler.(driver.DriverService).GetTodayStats(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGetTodayStatsArgs() interface{} {
	return driver.NewDriverServiceGetTodayStatsArgs()
}

func newDriverServiceGetTodayStatsResult() interface{} {
	return driver.NewDriverServiceGetTodayStatsResult()
}

func getCurrentOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGetCurrentOrderArgs)
	realResult := result.(*driver.DriverServiceGetCurrentOrderResult)
	success, err := handler.(driver.DriverService).GetCurrentOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGetCurrentOrderArgs() interface{} {
	return driver.NewDriverServiceGetCurrentOrderArgs()
}

func newDriverServiceGetCurrentOrderResult() interface{} {
	return driver.NewDriverServiceGetCurrentOrderResult()
}

func getWalletHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*driver.DriverServiceGetWalletArgs)
	realResult := result.(*driver.DriverServiceGetWalletResult)
	success, err := handler.(driver.DriverService).GetWallet(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDriverServiceGetWalletArgs() interface{} {
	return driver.NewDriverServiceGetWalletArgs()
}

func newDriverServiceGetWalletResult() interface{} {
	return driver.NewDriverServiceGetWalletResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Create(ctx context.Context, req *driver0.CreateDriverReq) (r *driver0.CreateDriverResp, err error) {
	var _args driver.DriverServiceCreateArgs
	_args.Req = req
	var _result driver.DriverServiceCreateResult
	if err = p.c.Call(ctx, "Create", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Get(ctx context.Context, req *driver0.GetDriverReq) (r *driver0.GetDriverResp, err error) {
	var _args driver.DriverServiceGetArgs
	_args.Req = req
	var _result driver.DriverServiceGetResult
	if err = p.c.Call(ctx, "Get", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) List(ctx context.Context, req *driver0.ListDriverReq) (r *driver0.ListDriverResp, err error) {
	var _args driver.DriverServiceListArgs
	_args.Req = req
	var _result driver.DriverServiceListResult
	if err = p.c.Call(ctx, "List", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Update(ctx context.Context, req *driver0.UpdateDriverReq) (r *driver0.UpdateDriverResp, err error) {
	var _args driver.DriverServiceUpdateArgs
	_args.Req = req
	var _result driver.DriverServiceUpdateResult
	if err = p.c.Call(ctx, "Update", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, req *driver0.DeleteDriverReq) (r *driver0.DeleteDriverResp, err error) {
	var _args driver.DriverServiceDeleteArgs
	_args.Req = req
	var _result driver.DriverServiceDeleteResult
	if err = p.c.Call(ctx, "Delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GoOnline(ctx context.Context, req *driver0.GoOnlineReq) (r *driver0.GoOnlineResp, err error) {
	var _args driver.DriverServiceGoOnlineArgs
	_args.Req = req
	var _result driver.DriverServiceGoOnlineResult
	if err = p.c.Call(ctx, "GoOnline", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetIdle(ctx context.Context, req *driver0.SetIdleReq) (r *driver0.SetIdleResp, err error) {
	var _args driver.DriverServiceSetIdleArgs
	_args.Req = req
	var _result driver.DriverServiceSetIdleResult
	if err = p.c.Call(ctx, "SetIdle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StartListening(ctx context.Context, req *driver0.StartListeningReq) (r *driver0.StartListeningResp, err error) {
	var _args driver.DriverServiceStartListeningArgs
	_args.Req = req
	var _result driver.DriverServiceStartListeningResult
	if err = p.c.Call(ctx, "StartListening", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GoOffline(ctx context.Context, req *driver0.GoOfflineReq) (r *driver0.GoOfflineResp, err error) {
	var _args driver.DriverServiceGoOfflineArgs
	_args.Req = req
	var _result driver.DriverServiceGoOfflineResult
	if err = p.c.Call(ctx, "GoOffline", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReportLocation(ctx context.Context, req *driver0.ReportLocationReq) (r *driver0.ReportLocationResp, err error) {
	var _args driver.DriverServiceReportLocationArgs
	_args.Req = req
	var _result driver.DriverServiceReportLocationResult
	if err = p.c.Call(ctx, "ReportLocation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DispatchOrder(ctx context.Context, req *driver0.DispatchOrderReq) (r *driver0.DispatchOrderResp, err error) {
	var _args driver.DriverServiceDispatchOrderArgs
	_args.Req = req
	var _result driver.DriverServiceDispatchOrderResult
	if err = p.c.Call(ctx, "DispatchOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AcceptOrder(ctx context.Context, req *driver0.AcceptOrderReq) (r *driver0.AcceptOrderResp, err error) {
	var _args driver.DriverServiceAcceptOrderArgs
	_args.Req = req
	var _result driver.DriverServiceAcceptOrderResult
	if err = p.c.Call(ctx, "AcceptOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RejectOrder(ctx context.Context, req *driver0.RejectOrderReq) (r *driver0.RejectOrderResp, err error) {
	var _args driver.DriverServiceRejectOrderArgs
	_args.Req = req
	var _result driver.DriverServiceRejectOrderResult
	if err = p.c.Call(ctx, "RejectOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelOrder(ctx context.Context, req *driver0.CancelOrderReq) (r *driver0.CancelOrderResp, err error) {
	var _args driver.DriverServiceCancelOrderArgs
	_args.Req = req
	var _result driver.DriverServiceCancelOrderResult
	if err = p.c.Call(ctx, "CancelOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DriverArrive(ctx context.Context, req *driver0.DriverArriveReq) (r *driver0.DriverArriveResp, err error) {
	var _args driver.DriverServiceDriverArriveArgs
	_args.Req = req
	var _result driver.DriverServiceDriverArriveResult
	if err = p.c.Call(ctx, "DriverArrive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StartTrip(ctx context.Context, req *driver0.StartTripReq) (r *driver0.StartTripResp, err error) {
	var _args driver.DriverServiceStartTripArgs
	_args.Req = req
	var _result driver.DriverServiceStartTripResult
	if err = p.c.Call(ctx, "StartTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EndTrip(ctx context.Context, req *driver0.EndTripReq) (r *driver0.EndTripResp, err error) {
	var _args driver.DriverServiceEndTripArgs
	_args.Req = req
	var _result driver.DriverServiceEndTripResult
	if err = p.c.Call(ctx, "EndTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyPassengerPhone(ctx context.Context, req *driver0.VerifyPassengerPhoneReq) (r *driver0.VerifyPassengerPhoneResp, err error) {
	var _args driver.DriverServiceVerifyPassengerPhoneArgs
	_args.Req = req
	var _result driver.DriverServiceVerifyPassengerPhoneResult
	if err = p.c.Call(ctx, "VerifyPassengerPhone", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPoolOrders(ctx context.Context, req *driver0.ListPoolOrdersReq) (r *driver0.ListPoolOrdersResp, err error) {
	var _args driver.DriverServiceListPoolOrdersArgs
	_args.Req = req
	var _result driver.DriverServiceListPoolOrdersResult
	if err = p.c.Call(ctx, "ListPoolOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GrabOrder(ctx context.Context, req *driver0.GrabOrderReq) (r *driver0.GrabOrderResp, err error) {
	var _args driver.DriverServiceGrabOrderArgs
	_args.Req = req
	var _result driver.DriverServiceGrabOrderResult
	if err = p.c.Call(ctx, "GrabOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListOrders(ctx context.Context, req *driver0.ListOrdersReq) (r *driver0.ListOrdersResp, err error) {
	var _args driver.DriverServiceListOrdersArgs
	_args.Req = req
	var _result driver.DriverServiceListOrdersResult
	if err = p.c.Call(ctx, "ListOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrder(ctx context.Context, req *driver0.GetOrderReq) (r *driver0.GetOrderResp, err error) {
	var _args driver.DriverServiceGetOrderArgs
	_args.Req = req
	var _result driver.DriverServiceGetOrderResult
	if err = p.c.Call(ctx, "GetOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTodayStats(ctx context.Context, req *driver0.GetTodayStatsReq) (r *driver0.TodayStatsResp, err error) {
	var _args driver.DriverServiceGetTodayStatsArgs
	_args.Req = req
	var _result driver.DriverServiceGetTodayStatsResult
	if err = p.c.Call(ctx, "GetTodayStats", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCurrentOrder(ctx context.Context, req *driver0.GetCurrentOrderReq) (r *driver0.CurrentOrderResp, err error) {
	var _args driver.DriverServiceGetCurrentOrderArgs
	_args.Req = req
	var _result driver.DriverServiceGetCurrentOrderResult
	if err = p.c.Call(ctx, "GetCurrentOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetWallet(ctx context.Context, req *driver0.GetWalletReq) (r *driver0.WalletResp, err error) {
	var _args driver.DriverServiceGetWalletArgs
	_args.Req = req
	var _result driver.DriverServiceGetWalletResult
	if err = p.c.Call(ctx, "GetWallet", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
